export const translations = {
    en: {
        // Menus
        startGame: "Start Game",
        settings: "Settings",
        about: "About",
        paused: "Paused",
        resume: "Resume",
        restartLevel: "Restart Level",
        exitToMenu: "Exit to Menu",
        back: "Back",
        
        // Settings
        masterVolume: "Master Volume",
        language: "Language",
        english: "English",
        arabic: "العربية",

        // Game UI & Prompts
        controls: "Use [QWD] or [Arrow Keys] to move. [Space] to Jump. [E] to interact.",
        books: "Books",
        keyInventory: "Key",
        continuePrompt: "Click or Press [Enter] to continue...",
        
        // Level Complete
        chamberCleared: "Level Complete!",
        storyFragments: "Story Fragments Unlocked",
        noNewFragments: "No new fragments found this time...",
        playAgain: "Play Again",
        nextLevel: "Next Level",
        finishGame: "Finish Game",
        proceedToFinal: "Proceed to Final Battle",

        // Final Level UI
        finalBattle: "Final Battle",
        hp: "HP",
        shield: "Shield",
        burst: "Reveal",
        weapon: "Weapon",
        overcharge: "Overcharge",
        ready: "Ready",

        // Ending Screen
        libraryRestored: "Chapter One Complete!",
        endingMessage: "With the Guardian freed, the library's core is stable once more, but the source of the corruption remains a mystery. The final book reveals not an ending, but the beginning of a new chapter. Lumin's adventure is far from over.",
        developer: "Developer",
        specialThanks: "Special Thanks",
        you: "You, the Player!",

        // Dialogues
        system: "System",
        narrator: "Mysterious Narrator",
        lumin: "Lumin",
        guardian: "Guardian of Knowledge",
        itemFound: "Item Found",
        locked: "Locked",
        keyFound: "You found a *rusty key*. It might open something nearby.",
        lockedDoor: "The door is locked. A key might be hidden somewhere in this chamber.",
        timedPuzzleFail: "Too slow... The mechanism has reset.",
        foundSpellbook: "You found the *Legendary Spellbook*! The library's magic feels calmer now.",
        fragment: "Fragment",
        level2IntroTitle: "The Deeper Halls",
        level2IntroText: "The air grows colder here. The library's magic feels... wilder. Be wary, the very passages seem to *shift and breathe* around you.",
        level3IntroTitle: "The Forbidden Archives",
        level3IntroText: "This is it... the heart of the library. The magic is raw, dangerous. The final secrets are guarded by the library's own *unstable architecture*.",
        
        // Final Level Dialogues
        finalLevelIntroTitle: "The Grand Chamber",
        finalLevelIntro1: "The air hums with immense power. This must be the heart of the library... and the source of its lockdown.",
        finalLevelIntro2: "So, a little spark has found its way to my sanctum. I am the *Guardian of Knowledge*, and you have come seeking what is forbidden.",
        finalLevelIntro3: "I'm not here to steal anything! I just want to find a way out. This library... it's trapped.",
        finalLevelIntro4: "Trapped? No. It is *protected*. But the magic has grown unstable over the centuries. It tests all who enter. If you truly wish to pass, you must prove your worth. Show me you can master the library's own *gifts*.",
        doubleJumpRune: "You absorbed the *Rune of Ascendance*! You can now JUMP a second time in mid-air!",
        weaponPickup: "You found the *Void Caster*! Press [Left-Click] to fire at the crystals and the Guardian!",
        checkpointReached: "Checkpoint Reached",
        checkpointText: "The ambient magic swirls, marking your progress. You will return here if you fall.",
        guardianFightStart: "Very well, little spark. The test begins! Let's see if your courage matches your curiosity!",
        crystalCollected: "A *Truth Crystal* has been destroyed! The Guardian's defenses are weakening!",
        allCrystalsCollected: "All crystals are destroyed! The Guardian is vulnerable! Now, attack its core!",
        guardianDefeated1: "Enough... You have proven yourself. You are not a plunderer, but a seeker. You see beyond the words on the page.",
        guardianDefeated2: "The library wasn't a prison for knowledge... it was a prison for *you*, wasn't it?",
        guardianPhase2Dialogue: "Insolence! The library's full power is mine to command!",
        guardianPhase3Dialogue: "You will be erased from every page, from every memory! THIS ENDS NOW!",
        guardianVulnerableDialogue: "The Guardian is vulnerable! Fire the Void Caster at its core!",
        endOfChapterOneTitle: "End of Chapter One",
        storyWillContinue: "The story will continue... Chapter Two is coming soon.",
        structureCollapse: "Structure collapsing...",
        mysteriousGlow: "✨ Mysterious Glow ✨",
        chapterEndText1: "You have defeated the Guardian and collected the crystals of truth...<br/>But this is just the beginning.",
        phase3Indicator: "⚡ Phase Three ⚡",
        phase2Indicator: "★ Phase Two ★",
        vulnerableIndicator: "Vulnerable!",
        guardianTitlePhase3: "🔥 Guardian - Full Wrath 🔥",
        guardianTitlePhase2: "⚡ Guardian - Growing Power ⚡",
        guardianTitleVulnerable: "✨ Guardian - Weakened ✨",
        guardianTitleDefault: "The Eternal Guardian",
        phaseLastAnnouncement: "🔥 Final Phase! 🔥",
        phaseNextAnnouncement: "⚡ Next Phase! ⚡",


        // About Screen
        aboutGameTitle: "Magical Library Adventure",
        aboutDeveloper: "Developer: Jamechx",
        aboutDescription: "Step into a world of mystery and magic! In Magical Library Adventure, you play as a young explorer trapped inside an enchanted library. Your goal is to collect scattered magical books, solve challenging puzzles, and uncover hidden secrets. Each book you find reveals a piece of an intriguing story, driving you to explore every corner of the magical world.",
        aboutExperienceTitle: "Experience:",
        aboutExperiencePoints: [
            "Engaging 2D side-scroller gameplay",
            "Interactive objects and puzzles",
            "Dialogue with letter-by-letter animation and unique sound effects",
            "Stunning visual and audio effects that bring the library to life",
            "Fully playable levels designed to challenge and entertain"
        ],
        aboutConnectTitle: "Connect with the Developer:",
        aboutConnectDescription: "Join Jamechx on this magical adventure and discover the secrets hidden within the library!",
    },
    ar: {
        // Menus
        startGame: "إبدأ اللعبة",
        settings: "الإعدادات",
        about: "حول اللعبة",
        paused: "متوقف مؤقتاً",
        resume: "استئناف",
        restartLevel: "إعادة المرحلة",
        exitToMenu: "الخروج للقائمة",
        back: "رجوع",

        // Settings
        masterVolume: "الصوت الرئيسي",
        language: "اللغة",
        english: "English",
        arabic: "العربية",

        // Game UI & Prompts
        controls: "استخدم [QWD] أو [مفاتيح الأسهم] للحركة. [Space] للقفز. [E] للتفاعل.",
        books: "الكتب",
        keyInventory: "مفتاح",
        continuePrompt: "انقر أو اضغط على [Enter] للمتابعة...",

        // Level Complete
        chamberCleared: "اكتملت المرحلة!",
        storyFragments: "شظايا القصة المكتشفة",
        noNewFragments: "لم يتم العثور على شظايا جديدة هذه المرة...",
        playAgain: "العب مجدداً",
        nextLevel: "المرحلة التالية",
        finishGame: "إنهاء اللعبة",
        proceedToFinal: "الانتقال إلى المعركة النهائية",

        // Final Level UI
        finalBattle: "المعركة النهائية",
        hp: "الصحة",
        shield: "الدرع",
        burst: "كشف",
        weapon: "السلاح",
        overcharge: "شحن زائد",
        ready: "جاهز",

        // Ending Screen
        libraryRestored: "اكتمل الفصل الأول!",
        endingMessage: "بتحرير الحارس، استقر قلب المكتبة مرة أخرى، لكن مصدر الفساد لا يزال لغزًا. الكتاب الأخير لا يكشف عن نهاية، بل عن بداية فصل جديد. مغامرة لومين لم تنته بعد.",
        developer: "المطور",
        specialThanks: "شكر خاص",
        you: "أنت، اللاعب!",

        // Dialogues
        system: "النظام",
        narrator: "الراوي الغامض",
        lumin: "لومين",
        guardian: "حارس المعرفة",
        itemFound: "تم العثور على عنصر",
        locked: "مغلق",
        keyFound: "لقد وجدت *مفتاحًا صدئًا*. قد يفتح شيئًا قريبًا.",
        lockedDoor: "الباب مغلق. قد يكون هناك مفتاح مخبأ في مكان ما في هذه الغرفة.",
        timedPuzzleFail: "بطيء جدًا... لقد أعادت الآلية ضبط نفسها.",
        foundSpellbook: "لقد وجدت *كتاب التعاويذ الأسطوري*! سحر المكتبة يبدو أهدأ الآن.",
        fragment: "شظية",
        level2IntroTitle: "القاعات الأعمق",
        level2IntroText: "الهواء يزداد برودة هنا. سحر المكتبة يبدو... أكثر جموحًا. كن حذرًا، فالممرات نفسها تبدو وكأنها *تتحول وتتنفس* من حولك.",
        level3IntroTitle: "الأرشيفات المحظورة",
        level3IntroText: "هذا هو... قلب المكتبة. السحر هنا خام وخطير. الأسرار النهائية محروسة بواسطة *بنية المكتبة غير المستقرة*.",

        // Final Level Dialogues
        finalLevelIntroTitle: "الغرفة الكبرى",
        finalLevelIntro1: "الهواء يضج بقوة هائلة. لابد أن هذا هو قلب المكتبة... ومصدر إغلاقها.",
        finalLevelIntro2: "إذًا، شرارة صغيرة وجدت طريقها إلى قدسي. أنا *حارس المعرفة*، وقد أتيت باحثًا عما هو محظور.",
        finalLevelIntro3: "أنا لست هنا لسرقة أي شيء! أريد فقط أن أجد مخرجًا. هذه المكتبة... إنها محاصرة.",
        finalLevelIntro4: "محاصرة؟ لا. إنها *محمية*. لكن السحر أصبح غير مستقر على مر القرون. إنه يختبر كل من يدخل. إذا كنت ترغب حقًا في المرور، يجب أن تثبت جدارتك. أرني أنك تستطيع إتقان *هدايا* المكتبة نفسها.",
        doubleJumpRune: "لقد امتصصت *رون الصعود*! يمكنك الآن القفز مرة ثانية في الهواء!",
        weaponPickup: "لقد وجدت *قاذف الفراغ*! اضغط [كليك يسار] لإطلاق النار على البلورات والحارس!",
        checkpointReached: "تم الوصول إلى نقطة الحفظ",
        checkpointText: "يدور السحر المحيط، معلمًا تقدمك. ستعود إلى هنا إذا سقطت.",
        guardianFightStart: "حسنًا جدًا، أيتها الشرارة الصغيرة. الاختبار يبدأ! دعنا نرى ما إذا كانت شجاعتك تضاهي فضولك!",
        crystalCollected: "تم تدمير *بلورة حقيقة*! دفاعات الحارس تضعف!",
        allCrystalsCollected: "تم تدمير كل البلورات! الحارس ضعيف! الآن، هاجم قلبه!",
        guardianDefeated1: "كفى... لقد أثبت نفسك. أنت لست ناهبًا، بل باحث. أنت ترى ما هو أبعد من الكلمات على الصفحة.",
        guardianDefeated2: "المكتبة لم تكن سجنًا للمعرفة... لقد كانت سجنًا *لك*، أليس كذلك؟",
        guardianPhase2Dialogue: "وقاحة! قوة المكتبة الكاملة تحت أمري!",
        guardianPhase3Dialogue: "سيتم محوك من كل صفحة، من كل ذكرى! هذا ينتهي الآن!",
        guardianVulnerableDialogue: "الحارس ضعيف! أطلق قاذف الفراغ على قلبه!",
        endOfChapterOneTitle: "نهاية الفصل الأول",
        storyWillContinue: "ستستمر القصة... الفصل الثاني قريباً.",
        structureCollapse: "انهيار الهيكل...",
        mysteriousGlow: "✨ لُمعان غامض ✨",
        chapterEndText1: "لقد هزمت الحارس وجمعت بلورات الحقيقة...<br/>لكن هذه مجرد البداية",
        phase3Indicator: "⚡ المرحلة الثالثة ⚡",
        phase2Indicator: "★ المرحلة الثانية ★",
        vulnerableIndicator: "ضعيف!",
        guardianTitlePhase3: "🔥 الحارس - غضب كامل 🔥",
        guardianTitlePhase2: "⚡ الحارس - قوة متزايدة ⚡",
        guardianTitleVulnerable: "✨ الحارس - ضعيف ✨",
        guardianTitleDefault: "الحارس الأبدي",
        phaseLastAnnouncement: "🔥 المرحلة الأخيرة! 🔥",
        phaseNextAnnouncement: "⚡ المرحلة التالية! ⚡",

        // About Screen
        aboutGameTitle: "مغامرة المكتبة السخرية",
        aboutDeveloper: "المطور: Jamechx",
        aboutDescription: "ادخل إلى عالم من الغموض والسحر! في مغامرة المكتبة السحرية، تلعب دور مستكشف شاب محاصر داخل مكتبة مسحورة. هدفك هو جمع الكتب السحرية المتناثرة وحل الألغاز الصعبة وكشف الأسرار الخفية. كل كتاب تجده يكشف عن جزء من قصة مثيرة، مما يدفعك لاستكشاف كل ركن من أركان هذا العالم السحري.",
        aboutExperienceTitle: "التجربة:",
        aboutExperiencePoints: [
            "لعب منصات ثنائي الأبعاد جذاب",
            "عناصر وألغاز تفاعلية",
            "حوارات مع رسوم متحركة حرفًا بحرف ومؤثرات صوتية فريدة",
            "مؤثرات بصرية وصوتية مذهلة تعيد المكتبة إلى الحياة",
            "مراحل قابلة للعب بالكامل مصممة للتحدي والترفيه"
        ],
        aboutConnectTitle: "تواصل مع المطور:",
        aboutConnectDescription: "انضم إلى Jamechx في هذه المغامرة السحرية واكتشف الأسرار الخفية داخل المكتبة!",
    }
};